# Generated by Django 4.2.4 on 2023-09-01 06:15

from django.db import migrations, models
import petstagram_second.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_picture',
            field=models.ImageField(upload_to='images', validators=[petstagram_second.photos.validators.image_max_size_validator]),
        ),
    ]
