# Generated by Django 4.2.4 on 2023-09-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-date_of_publication',)},
        ),
    ]
